//  ABMNZN SDK 2020-07-28-6xpzxs20
if (window.amazon == null || window.amazon.Login == null) {
    (function() {
    var h,m,n,q,w,x,y;function aa(a,b){if(null===a||void 0===a)a={};for(var c=1;c<arguments.length;c++){var d=arguments[c];if(null!==d&&void 0!==d)for(var e in d)a[e]=d[e]}return a}function z(a,b){var c=B.apply(void 0,arguments);ba("error",c);throw Error(c);}function B(a,b){var c=arguments,d=1;return a.replace(/%((%)|[sid])/g,function(a){if(a[2])return a[2];a=c[d++];"object"==typeof a&&window.JSON&&window.JSON.stringify&&(a=window.JSON.stringify(a));return a})}
    function ba(a,b){window.console&&window.console.log&&("function"==typeof b&&(b=b()),b=B("[Amazon.%s] %s",a,b),window.console.log(b))}function ea(a){a&&"delegate"===a||z("expected %s value to be %s but was %s","options.response_type","delegate",a)}function C(a,b,c){null==b&&z("missing %s",a);typeof b!=c&&z("expected %s to be a %s",a,c)}
    function D(a){var b=document.getElementById(a);b||(b=document.createElement("div"),b.setAttribute("id",a),b.setAttribute("width",0),b.setAttribute("height",0),b.setAttribute("style","position: absolute; left: -1000px; top: -1000px"),b.style.setAttribute&&b.style.setAttribute("cssText","position: absolute; left: -1000px; top: -1000px"),a=document.getElementById("amazon-root"),a||(a=document.createElement("div"),a.setAttribute("id","amazon-root"),document.body.appendChild(a)),a.appendChild(b));return b}
    function fa(){var a=D("amazon-client-credentials-root"),b=F(16),c=document.createElement("iframe");c.setAttribute("name",b);a.appendChild(c);0==document.getElementsByName(b).length&&(a.removeChild(c),c=document.createElement('<iframe name="'+b+'"/>'),a.appendChild(c));c.setAttribute("id",b);return b}function G(){this.a=[]}G.prototype.wait=function(a,b){this.a.push({ta:a,persist:!!b})};
    G.prototype.b=function(a){var b=this.a;this.a=[];for(var c=0;c<b.length;c++)b[c].persist&&this.a.push(b[c]);for(c=0;c<b.length;c++)b[c].ta.apply(void 0,arguments)};
    var H=function(){function a(){switch(f){case "t":return e("t"),e("r"),e("u"),e("e"),!0;case "f":return e("f"),e("a"),e("l"),e("s"),e("e"),!1;case "n":return e("n"),e("u"),e("l"),e("l"),null}g("Unexpected '"+f+"'")}function b(){for(;f&&" ">=f;)e()}function c(){var a,b="",c;if('"'===f)for(;e();){if('"'===f)return e(),b;if("\\"===f)if(e(),"u"===f){for(a=c=0;4>a;a+=1){var d=parseInt(e(),16);if(!isFinite(d))break;c=16*c+d}b+=String.fromCharCode(c)}else if("string"===typeof l[f])b+=l[f];else break;else b+=
    f}g("Bad string")}function d(){var a="";"-"===f&&(a="-",e("-"));for(;"0"<=f&&"9">=f;)a+=f,e();if("."===f)for(a+=".";e()&&"0"<=f&&"9">=f;)a+=f;if("e"===f||"E"===f){a+=f;e();if("-"===f||"+"===f)a+=f,e();for(;"0"<=f&&"9">=f;)a+=f,e()}a=+a;if(isFinite(a))return a;g("Bad number")}function e(a){a&&a!==f&&g("Expected '"+a+"' instead of '"+f+"'");f=t.charAt(k);k+=1;return f}function g(a){throw{name:"SyntaxError",message:a,Ga:k,text:t};}var k,f,l={'"':'"',"\\":"\\","/":"/",o:"\b",H:"\f",n:"\n",r:"\r",t:"\t"},
    t;var r=function(){b();switch(f){case "{":a:{var k={};if("{"===f){e("{");b();if("}"===f){e("}");var l=k;break a}for(;f;){l=c();b();e(":");Object.hasOwnProperty.call(k,l)&&g('Duplicate key "'+l+'"');k[l]=r();b();if("}"===f){e("}");l=k;break a}e(",");b()}}g("Bad object");l=void 0}return l;case "[":a:{l=[];if("["===f){e("[");b();if("]"===f){e("]");break a}for(;f;){l.push(r());b();if("]"===f){e("]");break a}e(",");b()}}g("Bad array");l=void 0}return l;case '"':return c();case "-":return d();default:return"0"<=
    f&&"9">=f?d():a()}};return function(a,c){t=a;k=0;f=" ";a=r();b();f&&g("Syntax error");return"function"===typeof c?function O(a,b){var d,e=a[b];if(e&&"object"===typeof e)for(d in e)if(Object.prototype.hasOwnProperty.call(e,d)){var f=O(e,d);void 0!==f?e[d]=f:delete e[d]}return c.call(a,b,e)}({"":a},""):a}}(),J=function(){function a(a){return 10>a?"0"+a:a}function b(a){d.lastIndex=0;return d.test(a)?'"'+a.replace(d,function(a){var b=k[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+
    '"':'"'+a+'"'}function c(a,d){var k=e,p=d[a];p&&"object"===typeof p&&"function"===typeof p.toJSON&&(p=p.toJSON(a));"function"===typeof f&&(p=f.call(d,a,p));switch(typeof p){case "string":return b(p);case "number":return isFinite(p)?String(p):"null";case "boolean":case "null":return String(p);case "object":if(!p)return"null";e+=g;var l=[];if("[object Array]"===Object.prototype.toString.apply(p)){var t=p.length;for(a=0;a<t;a+=1)l[a]=c(a,p)||"null";d=0===l.length?"[]":e?"[\n"+e+l.join(",\n"+e)+"\n"+
    k+"]":"["+l.join(",")+"]";e=k;return d}if(f&&"object"===typeof f)for(t=f.length,a=0;a<t;a+=1){if("string"===typeof f[a]){var E=f[a];(d=c(E,p))&&l.push(b(E)+(e?": ":":")+d)}}else for(E in p)Object.prototype.hasOwnProperty.call(p,E)&&(d=c(E,p))&&l.push(b(E)+(e?": ":":")+d);d=0===l.length?"{}":e?"{\n"+e+l.join(",\n"+e)+"\n"+k+"}":"{"+l.join(",")+"}";e=k;return d}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+
    1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var d=/[\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,e,g,k={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},f;return function(a,b,d){var k;g=e="";if("number"===typeof d)for(k=
    0;k<d;k+=1)g+=" ";else"string"===typeof d&&(g=d);if((f=b)&&"function"!==typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("JSON.stringify");return c("",{"":a})}}();function M(a){var b="",c;for(c in a)b&&(b+="&"),b+=encodeURIComponent(c)+"="+encodeURIComponent(a[c]+"");return b}
    (function(){function a(a,c){for(var b=0;b<c.length;b++){var e=c[b];""==e||a.b.hasOwnProperty(e)||(a.a.push(e),a.b[e]=1)}}m=function(b){this.a=[];b="string"==typeof b?b.split(/\s+/):b;this.b={};a(this,b)};m.prototype.contains=function(a){for(var b=0;b<a.a.length;b++)if(!this.b.hasOwnProperty(a.a[b]))return!1;return!0};m.prototype.add=function(b){a(this,b.a)};m.prototype.g=function(a){for(var b=0;b<this.a.length;b++)a(this.a[b])};m.prototype.toString=function(){return this.a.join(" ")}})();
    (function(){n={};var a=null;n.ba=function(){return a};n.i=function(b){C("domain",b,"string");b=b.replace(/^\s+|\s+$/g,"");var c="."+window.location.hostname;"."!=b.charAt(0)&&(b="."+b);c.indexOf(b)!=c.length-b.length&&z("Site domain must contain the current page's domain");a=b};n.O=function(){};n.O.prototype.getItem=function(){};n.O.setItem=function(){};n.O.removeItem=function(){}})();
    (function(){function a(){}a.prototype.getItem=function(a){a=(new RegExp("(?:^|;)\\s*"+escape(a).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=\\s*([^;]*)(?:;|$)")).exec(document.cookie);return null==a?null:unescape(a[1])};a.prototype.setItem=function(a,c,d){var b=null==d?"Fri, 31 Dec 9999 23:59:59 GMT":(new Date((new Date).getTime()+1E3*d)).toGMTString();var g=n.ba();g=null==g?"":";Domain="+g;var k=ha(N(window.location.href))?"":";Secure";document.cookie=a+"="+escape(c)+("session"==d?"":";Expires="+b)+g+
    ";Path=/"+k};a.prototype.removeItem=function(a){n.f.setItem(a,"null",0)};n.f=new a})();(function(){function a(a){this.a=a}a.prototype.getItem=function(a){return this.a.getItem(a)};a.prototype.setItem=function(a,c,d){this.a.setItem(a,c,d)};a.prototype.removeItem=function(a){n.f.removeItem(a)};n.B=new a(n.f)})();
    q={ua:function(a){var b=n.f.getItem("amazon_Login_auth_code_scope_cache");if(b)return b=H(b),b[a]},pa:function(a,b){var c={};c[a]=b;n.B.setItem("amazon_Login_auth_code_scope_cache",J(c),240)},qa:function(a,b,c){"bearer"==a.token_type&&(a=J({access_token:a.access_token,max_age:c,expiration_date:(new Date).getTime()+1E3*c,client_id:w.aa(),scope:b}),n.B.setItem("amazon_Login_state_cache",a,"session"))},R:function(){var a=n.B.getItem("amazon_Login_state_cache");return null!=a&&(a=H(a),null!=a&&a.expiration_date>
    (new Date).getTime())?(a.scope=new m(a.scope),a):null},P:function(){n.B.removeItem("amazon_Login_state_cache")}};function ia(){return window.XMLHttpRequest&&"withCredentials"in new window.XMLHttpRequest||"undefined"!==typeof window.XDomainRequest?!0:!1}
    function P(a,b,c,d,e,g){this.a=new Q(a,b,c);"string"==typeof d&&d||z("missing or invalid path: %s",d);this.u=d;"object"==typeof e&&(e=M(e));e&&"string"!=typeof e&&z("invalid query: %s",e);this.g=e||"";"object"==typeof g&&(g=M(g));g&&"string"!=typeof g&&z("invalid fragment: %s",g);this.b=g||""}
    function N(a){var b=function(){var b=document.createElement("div");b.innerHTML="<a></a>";b.firstChild.href=a;b.innerHTML=b.innerHTML;return b.firstChild}();""==b.host&&(b.href=b.href);return new P(b.protocol,b.hostname,function(){var a=b.port;a&&"0"!=a||(a=null);return a}(),function(){var a=b.pathname;a?"/"!=a[0]&&(a="/"+a):a="/";return a}(),b.search.substring(1),b.href.split("#")[1]||"")}h=P.prototype;h.scheme=function(){return this.a.scheme()};h.host=function(){return this.a.host()};h.port=function(){return this.a.port()};
    h.path=function(){return this.u};h.query=function(){return this.g};h.s=function(){return this.b};function ha(a){var b="http"==a.a.scheme();a=a.a.host();return b&&("localhost"==a||"127.0.0.1"==a)}h.toString=function(){var a=this.a.toString();a+=this.u;a+=this.g?"?"+this.g:"";return a+=this.b?"#"+this.b:""};
    function ja(a,b){return new P(void 0!==b.scheme?b.scheme:a.scheme(),void 0!==b.host?b.host:a.host(),void 0!==b.port?b.port:a.port(),void 0!==b.path?b.path:a.path(),void 0!==b.query?b.query:a.query(),void 0!==b.s?b.s:a.s())}
    function Q(a,b,c){var d;"string"==typeof a&&(d=a.match(/^(https?)(:(\/\/)?)?$/i))||z("missing or invalid scheme: %s",a);this.a="http"==d[1]?"http":"https";if(a="string"==typeof b&&b)"string"==typeof b&&b||z("missing or invalid input: %s",b),a=0!=b.replace(/^\s+|\s+$/g,"").length;a||z("missing or invalid host: %s",b);this.g=b;c&&((c+"").match(/^\d+$/)||z("invalid port: %s",c),80==c&&"http"==this.a||443==c&&"https"==this.a)&&(c=null);this.b=c?c+"":null}Q.prototype.scheme=function(){return this.a};
    Q.prototype.host=function(){return this.g};Q.prototype.port=function(){return this.b};Q.prototype.toString=function(){var a=this.a+"://";a+=this.g;return a+=this.b?":"+this.b:""};function R(a,b,c,d){return new P(a.a,a.g,a.b,b,c,d)}function F(a){for(var b="",c=0;c<a;c++)b+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62*Math.random()));return b}var S={},T=null;
    function ka(a,b){var c=la(a);var d=a.host().replace(/[^a-z0-9]/ig,"_");a.port()&&(d+="_"+a.port());d=B("amazon-proxy-%s-%s",a.scheme(),d);var e=document.getElementById(d);e||(e=document.createElement("iframe"),e.setAttribute("id",d),e.setAttribute("name",d),e.setAttribute("src",ma(a,c).toString()),D("amazon-proxy-root").appendChild(e));c=F(16);S[c]||(S[c]=new G);S[c].wait(b,!1);b={uri:na().toString(),proxy:d,topic:c,version:"3"};return R(a,"/sdk/2020-07-28-6xpzxs20/topic.html",b,"")}
    function la(a){T||(T=ua(),T.fa(a,function(a,c){(a=S[a])&&a.b(c)}));return T}function na(){return ja(N(window.location.href),{query:"",s:""})}function ma(a,b){b={uri:na().toString(),tr:b.name()};return R(a,"/ap/oa/proxy.html",{version:"3",build:"2020-07-28-6xpzxs20"},b)}var va=/^ABMNZNXDC;([\w\d_\-]+);(.*)$/;
    function xa(a){if("string"===typeof a){var b=a.match(va);if(b){a={};a.id=b[1];var c={};b=b[2].split("&");for(var d=0;d<b.length;d++){var e=b[d].split("=");2==e.length&&(c[e[0]]=decodeURIComponent(e[1].replace(/\+/g," ")))}a.data=c;return a}}return null}function ua(){var a=window.postMessage?"pm":"fr";window.__toucanForceTransport&&(a=window.__toucanForceTransport);if("pm"==a)a=new X;else if("fr"==a)a=new Y;else throw z("unknown transport: %s",a),Error();return a}function X(){this.a=void 0}
    X.prototype.name=function(){return"pm"};function ya(a){if(void 0===a.a){var b=a.a=new G;a=function(a){var d;(d=xa(a.data))&&b.b(a.origin,d.id,d.data)};window.addEventListener?window.addEventListener("message",a,!1):window.attachEvent?window.attachEvent("onmessage",a):z("cannot attach message event")}}X.prototype.fa=function(a,b){ya(this);var c=a.toString();this.a.wait(function(a,e,g){var d=N(window.location.href).a.toString();a!=c&&a!=d||b(e,g)},!0)};
    X.prototype.send=function(a,b,c){var d=a.a,e=H(J(c));setTimeout(function(){window.parent.postMessage(B("%s;%s;%s","ABMNZNXDC",b,M(e)),d.toString())},1)};function Y(){}Y.prototype.name=function(){return"fr"};Y.prototype.fa=function(a,b){window.__toucanInvokeFragment=function(a,d){b(a,d)}};
    Y.prototype.send=function(a,b,c){var d=a.query();(d=d||"")&&(d+="&");d=d+"ABMNZNXDC"+("="+F(8));a=ja(a,{query:d,s:B("%s;%s;%s","ABMNZNXDC",b,M(c))});b=document.createElement("iframe");b.setAttribute("src",a.toString());document.body.appendChild(b)};var za=window.location.href.split("#")[1]||"";if(za){var Aa=xa(za);Aa&&(document.documentElement.style.display="none","function"==typeof window.parent.parent.__toucanInvokeFragment&&window.parent.parent.__toucanInvokeFragment(Aa.id,Aa.data))}
    (function(){function a(a){var b=a.match(wa);b||z("invalid domain: %s",a);var d=b[2]?b[2].toLowerCase():"https";"https"!=d&&z("invalid domain: %s; scheme must be https",a);a=b[3];a.match(/^amazon\.[a-z\.]+$/)&&(a="www."+a);return new Q(d,a,b[5])}function b(a){a=aa({interactive:void 0,popup:!0,response_type:"token",response_mode:void 0,delegated_requests:void 0,direct_post_uri:void 0,state:void 0,scope:void 0,scope_data:void 0,optional_scope:void 0,"com.amazon.oauth2.options":void 0,workflow_data:void 0,
    pkce:!1,code_challenge:void 0,code_challenge_method:"S256"},a||{});C("options.response_type",a.response_type,"string");a.response_mode&&C("options.response_mode",a.response_mode,"string");a.direct_post_uri&&C("options.direct_post_uri",a.direct_post_uri,"string");if(!0===a[u.N]||a[u.j])a[u.na]="code";var b=a.delegated_requests;if(b){ea(a.response_type);a.scope&&z("options.scope is not supported for delegated authorization");a.scope_data&&z("options.scope_data is not supported for delegated authorization");
    a.optional_scope&&z("options.optional_scope is not supported for delegated authorization");a.interactive?a.interactive!=v.ALWAYS&&z("options.interactive should be '"+v.ALWAYS+"' for delegated authorization"):a.interactive=v.ALWAYS;for(var oa={},f=0;f<b.length;f++){var k=b[f],l=c(a,k);oa[k.request_id]=l}a.delegated_requests=oa}else if(d(a,"missing options.scope"),e(a),g(a),a.interactive?a.interactive!=v.L&&a.interactive!=v.ALWAYS&&a.interactive!=v.NEVER&&z("expected options.interactive to be one of '"+
    v.L+"', '"+v.ALWAYS+"', or '"+v.NEVER+"'"):a.interactive=v.L,a.optional_scope){a.optional_scope.constructor!==Array&&"string"!=typeof a.optional_scope&&z("expected options.optional_scope to be a string or array");a.interactive!=v.NEVER&&z("options.optional_scope is only supported for options.interactive = never");b=new m(a.optional_scope);a.scope.add(b);var p={id_token:{}};b.g(function(a){p.id_token[a]={essential:!1}});a.optional_scope=J(p)}return a}function c(a,b){b.response_mode&&z("response_mode is not supported in delegated requests");
    b.direct_post_uri&&z("direct_post_uri is not supported in delegated requests");"popup"in b&&z("popup is not supported in delegated requests");b.interactive&&z("interactive mode is not supported in delegated requests");b.optional_scope&&z("optional_scope is not supported in delegated requests");b.delegated_requests&&z("delegated_requests is not supported in delegated requests");null==b.response_type&&(b.response_type="token");d(b,"missing 'scope' in delegated request");b.scope=b.scope.toString();e(b);
    g(a);C("request_id",b.request_id,"string");b.client_id&&!b.client_id.match(O)&&z("invalid client_id format: %s",b.client_id);a={};for(var c in b)"request_id"!=c&&(a[c]=b[c]);return a}function d(a,b){a.scope||z(b);a.scope.constructor!==Array&&"string"!=typeof a.scope&&z("expected scope to be a string or array");a.scope=new m(a.scope)}function e(a){a.scope_data&&(a.scope_data=J(a.scope_data))}function g(a){if(a.workflow_data){var b={};b.workflow_data=a.workflow_data;a["com.amazon.oauth2.options"]=J(b)}}
    function k(a){var b=(void 0!==window.screenX?window.screenX:window.screenLeft)+Math.floor(((void 0!==window.outerWidth?window.outerWidth:document.documentElement.clientWidth)-800)/2),d=(void 0!==window.screenY?window.screenY:window.screenTop)+Math.floor(((void 0!==window.outerHeight?window.outerHeight:document.documentElement.clientHeight)-540)/2);b=B("left=%s,top=%s,width=%s,height=%s,scrollbars=1",0>b?0:b,0>d?0:d,800,540);L=window.open(a.toString(),"amazonloginpopup",b)}function f(){null!=L&&("function"==
    typeof L.close&&L.close(),L=null)}function l(a,b,d){b={client_id:U,redirect_uri:b,response_type:a.response_type,language:pa,ui_locales:qa};a["com.amazon.oauth2.options"]&&(b["com.amazon.oauth2.options"]=a["com.amazon.oauth2.options"]);a.response_mode&&(b.response_mode=a.response_mode);a.scope&&(b.scope=a.scope.toString());a.direct_post_uri&&(b.direct_post_uri=a.direct_post_uri);a.scope_data&&(b.scope_data=a.scope_data);ra&&(b.sandbox=!0);a.state&&(b.state=a.state);d&&(b.exac=d);a.delegated_requests&&
    (b.delegated_requests=J(a.delegated_requests));a[u.j]&&(b[u.j]=a[u.j],b[u.M]=a[u.M]);!0!==a[u.N]||a[u.j]||(b[u.j]=x.va(b.client_id,b.redirect_uri),b[u.M]="S256");return R(K,"/ap/oa",b)}function t(a,b,d){V=!1;b.access_token?w.X(b,b.scope):d&&n.f.removeItem(w.l);b.code&&!0===a.a[u.N]&&q.pa(b.code,b.scope);a.ia(b);a=ca;ca=[];for(b=0;b<a.length;b++)A(a[b])}function r(a,b,d,c){var e=M(a);!d&&c?(a=N(b),a=ja(a,{s:e})):(b+=-1==b.indexOf("?")?"?":"&",b+=e,a=N(b));e=N(window.location.href);"https"==a.scheme()||
    ha(a)||z("attempted redirect to %s but scheme is not HTTPS",b);a.host()!=e.host()&&z("attempted redirect to %s but it does not match current host %s",a.host(),e.host());!d&&c?window.top.location.href=a.toString():(f(),window.location.href=b)}function p(a){var b=this;this.a=a;this.g=null;this.T=[];this.u=null;this.b={status:null,onComplete:function(a){"string"!=typeof a&&"function"!=typeof a&&z("onComplete expects handler parameter to be a function or a string");var d=b.b.status==W.V;"string"==typeof a?
    d?r(b.u,a,b.a.popup,"token"==b.a.response_type):b.g=a:"function"==typeof a&&(d?setTimeout(function(){a(b.b)},0):b.T.push(a));return b.b}}}function A(a){var b=a.a,d=null;if(b.delegated_requests)I(a,null);else{if(b.interactive==v.ALWAYS)q.P();else{var c=null;w.ha()&&(c=n.f.getItem(w.l));if(d=q.R())"token"==b.response_type&&b.scope.add(d.scope),c?c!=d.access_token&&(q.P(),d=null):c=d.access_token;if(d&&d.scope.contains(b.scope)&&"token"==b.response_type){var e={access_token:d.access_token,token_type:"bearer",
    expires_in:Math.floor((d.expiration_date-(new Date).getTime())/1E3),scope:d.scope.toString()};null!=b.state&&(e.state=b.state)}else if(b.interactive==v.NEVER&&b.popup){if(V){ca.push(a);a.U(W.ma);return}if(c){E(a,c);return}e={error:"invalid_grant",error_description:"invalid grant"}}if(e){setTimeout(function(){a.ia(e)},0);return}}I(a,c)}}function I(a,b){var d=a.a;if(d.popup)V=!0,d=ka(K,function(b){f();t(a,b,!0)}),b=l(a.a,d,b),k(b,a);else{var c=a.g;c||z("Missing redirectUrl for redirect flow");window.top.location.href=
    l(d,N(c+""),b).toString()}}function E(a,b){V=!0;var d=D("amazon-client-credentials-root"),c=fa(),e=document.createElement("form");d.appendChild(e);e.setAttribute("method","POST");e.setAttribute("target",c);var f=ka(K,function(b){d.removeChild(e);var g=document.getElementById(c);null!=g&&null!=g.parentNode&&g.parentNode.removeChild(g);null==b&&(b={error:"server_error",description:"Server error."});t(a,b,!1)}),g=a.a;b={client_id:U,exac:b,grant_type:"client_credentials",redirect_uri:f,response_type:g.response_type,
    scope:g.scope};null!=g.state&&(b.state=g.state);null!=g.response_mode&&(b.response_mode=g.response_mode);null!=g.direct_post_uri&&(b.direct_post_uri=g.direct_post_uri);null!=g.scope_data&&(b.scope_data=g.scope_data);null!=g.optional_scope&&(b.claims=g.optional_scope);null!=g["com.amazon.oauth2.options"]&&(b["com.amazon.oauth2.options"]=g["com.amazon.oauth2.options"]);e.setAttribute("action",R(K,"/ap/oa",b).toString());e.submit()}w={D:{NorthAmerica:"NA",Europe:"EU",AsiaPacific:"APAC",China:"CN"},ka:{N:"pkce",
    M:"code_challenge_method",j:"code_challenge",na:"response_type"},l:"amazon_Login_accessToken"};var u=w.ka,O=/^[\w\-\.]+$/,wa=/^((http|https):\/\/)?([a-z0-9\-\.]+)(:(\d+))?\/?$/i,v={ALWAYS:"always",L:"auto",NEVER:"never"},L=null,V=!1,ca=[],W={ma:"queued",ja:"in_progress",V:"complete"},U=void 0;w.aa=function(){return U};w.za=function(a){a.match(O)||z("invalid client ID: %s",a);U=a};var da="na.account.amazon.com",K=new Q("https",da,null),sa=new Q("https","api.amazon.com",null);w.ba=function(){return da};
    w.$=function(){return sa};var ra=!1;w.Da=function(a){"number"==typeof a&&(a=!!a);C("sandboxMode",a,"boolean");ra=a};w.i=function(b){K=a(b);da=b};w.A=function(b){sa=a(b)};w.Ca=function(a){a&&(a===w.D.Europe?(w.i("https://eu.account.amazon.com"),w.A("https://api.amazon.co.uk")):a===w.D.AsiaPacific?(w.i("https://apac.account.amazon.com"),w.A("https://api.amazon.co.jp")):a===w.D.China?(w.i("https://www.amazon.cn"),w.A("https://api.amazon.cn")):(w.i("https://na.account.amazon.com"),w.A("https://api.amazon.com")))};
    var pa="";w.Aa=function(a){pa=a};var qa="";w.Ba=function(a){qa=a};w.wa=function(){return K};var ta=!1;w.ha=function(){return ta};w.Ea=function(a){null==a?z("missing useCookie"):"number"==typeof a?a=!!a:"boolean"!=typeof a&&z("expected useCookie to be a boolean");ta=a};w.X=function(a,b){var d=parseInt(a.expires_in,10);d=60>=d?d:d-Math.min(Math.floor(.1*d),300);q.qa(a,b,d);w.ha()?n.f.setItem(w.l,a.access_token,d):n.f.removeItem(w.l)};p.prototype.ia=function(a){this.u=a;aa(this.b,a);this.U(W.V);for(a=
    0;a<this.T.length;a++)this.T[a](this.b);null!=this.g&&r(this.u,this.g,this.a.popup,"token"==this.a.response_type)};p.prototype.U=function(a){this.b.status=a};w.W=function(a,d){2>arguments.length&&z("authorize expects two arguments (options, next)");a&&"object"!=typeof a&&z("authorize expects options parameter to be an object");null!=d&&"function"!=typeof d&&"string"!=typeof d&&z("authorize expects next parameter to be a function or a string");a=b(a);var c=new p(a),e=c.b;c.U(W.ja);if(null!=d)e.onComplete(d);
    a.popup||"string"==typeof d?A(c):z("next must be redirect URI if !options.popup");return e}})();
    (function(){function a(a,c){try{var b=H(a)}catch(e){b=null}b&&b.Error?(a={success:!1},a.error=B("%s: %s",b.Error.Code||"UnknownError",b.Error.Message||"An unknown error occurred"),c(a)):b&&b.Profile?(a={success:!0},a.profile=b.Profile,c(a)):(a={success:!1,error:"UnknownError: Incomprehensible response from profile endpoint"},c(a))}y={ga:function(b,c){if(null==c&&"function"==typeof b)c=b,w.W({scope:"profile"},function(a){null==a.error?y.ga(a.access_token,c):c({success:!1,error:a.error})});else if(C("accessToken",
    b,"string"),C("callback",c,"function"),ia()){b=R(w.wa(),"/ap/user/profile",{access_token:b},"").toString();if(window.XDomainRequest){var d=new window.XDomainRequest;d.onload=function(){a(d.responseText,c)}}else{var e=!1;d=new window.XMLHttpRequest;d.onreadystatechange=function(){e||4!=d.readyState||(e=!0,a(d.responseText,c))}}d.open("GET",b,!0);d.send()}else c({success:!1,error:"UnsupportedOperation: Cannot retrieve profile in this browser"})}}})();
    (function(){function a(a,b){a={grant_type:"authorization_code",client_id:a.client_id,redirect_uri:decodeURIComponent(a.redirect_uri),code_verifier:a.code_verifier,code:b};return J(a)}function b(){var a=n.f.getItem(x.C);return a?H(a):null}function c(){var a=q.R();return a?{success:!0,access_token:a.access_token,token_type:"bearer",expires_in:Math.floor((a.expiration_date-(new Date).getTime())/1E3),scope:a.scope.toString()}:null}x={C:"amazon_Login_pkce_params",la:240,va:function(a,c){var d,e=b();e&&
    (e.client_id!=a?n.f.removeItem(x.C):e.code_verifier&&(d=e.code_verifier));if(!d){d="";for(e=128;0<e;--e)d+="0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"[Math.floor(62*Math.random())];d=encodeURIComponent(d)}a={client_id:a,code_verifier:d,redirect_uri:encodeURIComponent(c)};n.f.setItem(x.C,J(a),x.la);a=Z.hash.J.hash(d);return Z.h.oa.I(a)},ya:function(d,e){if(null==d&&null==e)return c();var g={};if("function"!==typeof window.XMLHttpRequest)g.success=!1,g.error="UnsupportedOperation: Cannot retrieve token in this browser",
    e(g);else{C("code",d,"string");C("callback",e,"function");var k=b();if(k){g=a(k,d);var f=!1,l=new window.XMLHttpRequest;l.onreadystatechange=function(){if(!f&&4==l.readyState){f=!0;try{var a=H(l.responseText);n.f.removeItem(x.C)}catch(A){a=null}var b={};if(a&&a.Error)b.success=!1,b.error=B("%s: %s",a.Error.Code||"UnknownError",a.Error.Message||"An unknown error occurred");else if(a&&a.access_token){b.success=!0;b.access_token=a.access_token;b.token_type=a.token_type;b.expires_in=a.expires_in;var c=
    q.ua(d);c&&w.X(a,c)}else b.success=!1,b.error="UnknownError: Incomprehensible response from token endpoint";e(b)}};l.open("POST",w.$()+"/auth/O2/token",!0);l.setRequestHeader("Content-Type","application/json");l.send(g)}else g.success=!1,g.error="UnsupportedOperation: Cookie amazon_Login_pkce_params not found. Cannot retrieve token without cookie.",e(g)}}}})();
    (function(){function a(a,e){ia()||c("UnsupportedOperation: Cannot remotely logout in this browser",e);var d=R(w.$(),"/auth/relyingPartyLogout",null,null).toString(),k={};k.token=a;k.token_type="bearer";if(window.XDomainRequest){var f=new window.XDomainRequest;f.onload=function(){b(f.responseText,e)}}else{var l=!1;f=new window.XMLHttpRequest;f.onreadystatechange=function(){l||4!=f.readyState||(l=!0,b(f.responseText,e))}}f.open("POST",d,!0);f.send(J(k))}function b(a,b){try{var d=H(a).response}catch(f){d=
    void 0}if(!d||d.error){a="UnknownError";var e="An unknown error ocurred";d&&d.error&&d.error.code&&d.error.message&&(a=d.error.code,e=d.error.message);e=B("%s: %s",a,e)}c(e,b)}function c(a,b){a&&ba("logout",a);b&&"function"==typeof b&&b()}w.xa=function(){var b=n.f.getItem(w.l),c=q.R();b&&n.f.removeItem(w.l);!b&&c&&(b=c.access_token);q.P();b&&a(b,void 0)}})();window.amazon=window.amazon||{};window.amazon.Login=window.amazon.Login||{};window.amazon.Login.getClientId=function(){return w.aa()};
    window.amazon.Login.setClientId=function(a){return w.za(a)};window.amazon.Login.setDomain=function(a){return w.i(a)};window.amazon.Login.setAPIDomain=function(a){return w.A(a)};window.amazon.Login.setSandboxMode=function(a){return w.Da(a)};window.amazon.Login.setSiteDomain=function(a){return n.i(a)};window.amazon.Login.Region=w.D;window.amazon.Login.setRegion=function(a){return w.Ca(a)};window.amazon.Login.setLanguage=function(a){return w.Aa(a)};window.amazon.Login.setLanguageHint=function(a){return w.Ba(a)};
    window.amazon.Login.setUseCookie=function(a){return w.Ea(a)};window.amazon.Login.authorize=function(a,b){return w.W(a,b)};window.amazon.Login.logout=function(){return w.xa()};window.amazon.Login.retrieveProfile=function(a,b){return y.ga(a,b)};window.amazon.Login.retrieveToken=function(a,b){return x.ya(a,b)};if("function"==typeof window.onAmazonLoginReady)window.onAmazonLoginReady();var Z={Ka:{},hash:{},Pa:{},mode:{},Qa:{},h:{},Y:{La:function(a){this.toString=function(){return"CORRUPT: "+this.message};this.message=a},ea:function(a){this.toString=function(){return"INVALID: "+this.message};this.message=a},Ia:function(a){this.toString=function(){return"BUG: "+this.message};this.message=a},Ra:function(a){this.toString=function(){return"NOT READY: "+this.message};this.message=a}},c:{Ha:function(a,b,c){a=Z.c.da(a.slice(b/32),32-(b&31)).slice(1);return void 0===c?a:Z.c.ra(a,c-b)},Na:function(a,
    b,c){var d=Math.floor(-b-c&31);return((b+c-1^b)&-32?a[b/32|0]<<32-d^a[b/32+1|0]>>>d:a[b/32|0]>>>d)&(1<<c)-1},concat:function(a,b){if(0===a.length||0===b.length)return a.concat(b);var c=a[a.length-1],d=Z.c.S(c);return 32===d?a.concat(b):Z.c.da(b,d,c|0,a.slice(0,a.length-1))},v:function(a){var b=a.length;return 0===b?0:32*(b-1)+Z.c.S(a[b-1])},ra:function(a,b){if(32*a.length<b)return a;a=a.slice(0,Math.ceil(b/32));var c=a.length;b&=31;0<c&&b&&(a[c-1]=Z.c.w(b,a[c-1]&2147483648>>b-1,1));return a},w:function(a,
    b,c){return 32===a?b:(c?b|0:b<<32-a)+1099511627776*a},S:function(a){return Math.round(a/1099511627776)||32},Ma:function(a,b){if(Z.c.v(a)!==Z.c.v(b))return!1;var c=0,d;for(d=0;d<a.length;d++)c|=a[d]^b[d];return 0===c},da:function(a,b,c,d){var e;for(void 0===d&&(d=[]);32<=b;b-=32)d.push(c),c=0;if(0===b)return d.concat(a);for(e=0;e<a.length;e++)d.push(c|a[e]>>>b),c=a[e]<<32-b;e=a.length?a[a.length-1]:0;a=Z.c.S(e);d.push(Z.c.w(b+a&31,32<b+a?c:d.pop(),1));return d},Oa:function(a,b){return[a[0]^b[0],a[1]^
    b[1],a[2]^b[2],a[3]^b[3]]},Ja:function(a){var b;for(b=0;b<a.length;++b){var c=a[b];a[b]=c>>>24|c>>>8&65280|(c&65280)<<8|c<<24}return a}}};Z.h.Fa={I:function(a){var b="",c=Z.c.v(a),d,e;for(d=0;d<c/8;d++)0===(d&3)&&(e=a[d/4]),b+=String.fromCharCode(e>>>8>>>8>>>8),e<<=8;return decodeURIComponent(escape(b))},K:function(a){a=unescape(encodeURIComponent(a));var b=[],c,d=0;for(c=0;c<a.length;c++)d=d<<8|a.charCodeAt(c),3===(c&3)&&(b.push(d),d=0);c&3&&b.push(Z.c.w(8*(c&3),d));return b}};
    Z.h.F={Z:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",I:function(a,b,c){var d="",e=0,g=Z.h.F.Z,k=0,f=Z.c.v(a);c&&(g=g.substr(0,62)+"-_");for(c=0;6*d.length<f;)d+=g.charAt((k^a[c]>>>e)>>>26),6>e?(k=a[c]<<6-e,e+=26,c++):(k<<=6,e-=6);for(;d.length&3&&!b;)d+="=";return d},K:function(a,b){a=a.replace(/\s|=/g,"");var c=[],d=0,e=Z.h.F.Z,g=0;b&&(e=e.substr(0,62)+"-_");for(b=0;b<a.length;b++){var k=e.indexOf(a.charAt(b));if(0>k)throw new Z.Y.ea("this isn't base64!");26<d?(d-=26,c.push(g^
    k>>>d),g=k<<32-d):(d+=6,g^=k<<32-d)}d&56&&c.push(Z.c.w(d&56,g,1));return c}};Z.h.oa={I:function(a){return Z.h.F.I(a,1,1)},K:function(a){return Z.h.F.K(a,1)}};Z.hash.J=function(a){this.H[0]||Ba(this);a?(this.G=a.G.slice(0),this.o=a.o.slice(0),this.m=a.m):this.reset()};Z.hash.J.hash=function(a){a=(new Z.hash.J).update(a);var b,c=a.o,d=a.G;c=Z.c.concat(c,[Z.c.w(1,1)]);for(b=c.length+2;b&15;b++)c.push(0);c.push(Math.floor(a.m/4294967296));for(c.push(a.m|0);c.length;)Ca(a,c.splice(0,16));a.reset();return d};
    Z.hash.J.prototype={reset:function(){this.G=this.ca.slice(0);this.o=[];this.m=0;return this},update:function(a){"string"===typeof a&&(a=Z.h.Fa.K(a));var b=this.o=Z.c.concat(this.o,a);var c=this.m;a=this.m=c+Z.c.v(a);if(9007199254740991<a)throw new Z.Y.ea("Cannot hash more than 2^53 - 1 bits");if("undefined"!==typeof Uint32Array){var d=new Uint32Array(b),e=0;for(c=512+c-(512+c&511);c<=a;c+=512)Ca(this,d.subarray(16*e,16*(e+1))),e+=1;b.splice(0,16*e)}else for(c=512+c-(512+c&511);c<=a;c+=512)Ca(this,
    b.splice(0,16));return this},ca:[],H:[]};
    function Ca(a,b){var c,d,e=a.G,g=a.H,k=e[0],f=e[1],l=e[2],t=e[3],r=e[4],p=e[5],A=e[6],I=e[7];for(a=0;64>a;a++)16>a?c=b[a]:(c=b[a+1&15],d=b[a+14&15],c=b[a&15]=(c>>>7^c>>>18^c>>>3^c<<25^c<<14)+(d>>>17^d>>>19^d>>>10^d<<15^d<<13)+b[a&15]+b[a+9&15]|0),c=c+I+(r>>>6^r>>>11^r>>>25^r<<26^r<<21^r<<7)+(A^r&(p^A))+g[a],I=A,A=p,p=r,r=t+c|0,t=l,l=f,f=k,k=c+(f&l^t&(f^l))+(f>>>2^f>>>13^f>>>22^f<<30^f<<19^f<<10)|0;e[0]=e[0]+k|0;e[1]=e[1]+f|0;e[2]=e[2]+l|0;e[3]=e[3]+t|0;e[4]=e[4]+r|0;e[5]=e[5]+p|0;e[6]=e[6]+A|0;e[7]=
    e[7]+I|0}function Ba(a){function b(a){return 4294967296*(a-Math.floor(a))|0}for(var c=0,d=2,e,g;64>c;d++){g=!0;for(e=2;e*e<=d;e++)if(0===d%e){g=!1;break}g&&(8>c&&(a.ca[c]=b(Math.pow(d,.5))),a.H[c]=b(Math.pow(d,1/3)),c++)}}"undefined"!==typeof module&&module.sa&&(module.sa=Z);"function"===typeof define&&define([],function(){return Z});
    
    })();
    }