export const DominantCategories = [
    { 'title': 'All', 'value': 'All' },
    { 'title': 'Alexa Skills', 'value': 'Alexa Skills' },
    { 'title': 'Amazon Custom', 'value': 'Amazon Custom' },
    { 'title': 'Amazon.com', 'value': 'Amazon.com' },
    { 'title': 'AmazonBasics', 'value': 'AmazonBasics' },
    { 'title': 'APS', 'value': 'APS' },
    { 'title': 'Arts, Crafts, and Sewing', 'value': 'Arts, Crafts, and Sewing' },
    { 'title': 'Automotive', 'value': 'Automotive' },
    { 'title': 'AWS-AP', 'value': 'AWS-AP' },
    { 'title': 'Baby', 'value': 'Baby' },
    { 'title': 'Beauty', 'value': 'Beauty' },
    { 'title': 'Books', 'value': 'Books' },
    { 'title': 'Camera and Photo', 'value': 'Camera and Photo' },
    { 'title': 'Collectibles', 'value': 'Collectibles' },
    { 'title': 'Computers', 'value': 'Computers' },
    { 'title': 'Courses', 'value': 'Courses' },
    { 'title': 'Credit Cards', 'value': 'Credit Cards' },
    { 'title': 'Electronics', 'value': 'Electronics' },
    { 'title': 'Fresh', 'value': 'Fresh' },
    { 'title': 'Gift Cards', 'value': 'Gift Cards' },
    { 'title': 'Gourmet', 'value': 'Gourmet' },
    { 'title': 'Grocery', 'value': 'Grocery' },
    { 'title': 'Handmade', 'value': 'Handmade' },
    { 'title': 'Home and Garden', 'value': 'Home and Garden' },
    { 'title': 'Home Improvement', 'value': 'Home Improvement' },
    { 'title': 'HPC', 'value': 'HPC' },
    { 'title': 'Industrial and Scientific', 'value': 'Industrial and Scientific' },
    { 'title': 'Kindle Store', 'value': 'Kindle Store' },
    { 'title': 'Launchpad', 'value': 'Launchpad' },
    { 'title': 'Local Services', 'value': 'Local Services' },
    { 'title': 'Magazines and Newspapers', 'value': 'Magazines and Newspapers' },
    { 'title': 'Merchants', 'value': 'Merchants' },
    { 'title': 'Mobile Apps Store', 'value': 'Mobile Apps Store' },
    { 'title': 'Movies & TV', 'value': 'Movies & TV' },
    { 'title': 'MP3 Downloads', 'value': 'MP3 Downloads' },
    { 'title': 'Music', 'value': 'Music' },
    { 'title': 'Musical Instruments', 'value': 'Musical Instruments' },
    { 'title': 'Office Products', 'value': 'Office Products' },
    { 'title': 'Prime Pantry', 'value': 'Prime Pantry' },
    { 'title': 'Retail Help', 'value': 'Retail Help' },
    { 'title': 'RPS', 'value': 'RPS' },
    { 'title': 'Softlines', 'value': 'Softlines' },
    { 'title': 'Software', 'value': 'Software' },
    { 'title': 'Sports & Outdoors', 'value': 'Sports & Outdoors' },
    { 'title': 'Toys', 'value': 'Toys' },
    { 'title': 'Uncategorized', 'value': 'Uncategorized' },
    { 'title': 'Vehicles', 'value': 'Vehicles' },
    { 'title': 'Video Games', 'value': 'Video Games' },
    { 'title': 'Video On Demand', 'value': 'Video On Demand' },
    { 'title': 'Video Shorts', 'value': 'Video Shorts' },
    { 'title': 'Warehouse Deals', 'value': 'Warehouse Deals' },
    { 'title': 'Wireless', 'value': 'Wireless' }
];